### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.deprecation#20]
I'd like to cut a new release of this package.
Could you please add me as PyPI maintainer?

Cc-ing current PyPI maintainers:

@mcdonc @freddrake @jamadden @menesis @tseaver

**Comment by tseaver** [comment]
Invite created.

**Comment by icemac** [comment]
I just created https://pypi.org/project/zope.deprecation/5.0/.
Thank you @tseaver!
